[package]
name = "minicat"
version = "1.1.0"
authors = ["yeeming <yeeming0771@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
